name: CanineSMP
version: '${project.version}'
main: com.trxsh.caninesmp.Main
api-version: 1.19
authors: [ trxsh ]
description: smp idea personally made by me
commands:
  locatedog:
    description: locates a player's dog.
    usage: /<command>
  teleportdog:
    description: teleports a player's dog to them.
    usage: /<command>
  doghealth:
    description: shows a player their dog's health.
    usage: /<command>
  dogstats:
    description: shows a player this dog's stats on the scoreboard.
    usage: /<command>
  unbandataplayer:
    description: unbans a player who was death-banned.
    usage: /<command>
  giverevivetoken:
    description: gives a player a revive token.
    usage: /<command>
  tradedoghealth:
    description: restores you to full health, but at the expense of your dog's health.
    usage: /<command>
  toggledog:
    description: toggles your dog.
    usage: /<command>
  toggledogattack:
    description: toggles atttacking of player's dogs.
    usage: /<command>
  stopattacking:
    description: stops your dog from attacking the current target.
    usage: /<command>
